version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - echo Installing hugo
      - curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.70.0/hugo_0.70.0_Linux-64bit.deb
      - dpkg -i hugo.deb
      - hugo version
  pre_build:
    commands:
  build:
    commands:
      # Build
      - hugo -v
  post_build:
    commands:
      # Post Build
artifacts:
  base-directory: 'public'
  files:
    - '**/*'